name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Restart
        run: |
          cd {{ secrets.DEPLOY_PATH }}
          git pull
          sudo systemctl restart pasteapp
